### ISSUE TITLE
Question on breakout jps

### ISSUE THREAD

**Issue by timbit123** [TheButlah/slimevr_pcb#23]
I'm trying to flash the wimos with BNO085 (slimevr one) I soldered the jp1 and jp2 and still cannot get any values on all board. I'm not sure what I'm doing wrong? thx

**Comment by TheButlah** [comment]
Hey sorry, there's not enough info to help u here. Also it's been a long time so my memory is rusty. Best to ask others in the slimevr discord. You can show them the schematics from this repo

**Comment by timbit123** [comment]
ok thanks, I will ask @Gammelstulle, I think he have the same configuration as me
